[provider]
cluster = "localnet"
wallet = "./tests/test-keypairs/test-key.json"

[programs.mainnet]
cardinal_rewards_center = "E2Wc4racSRRp8EBrMH3n1AYSjuFt4JiLdh14J58UiyDu"

[programs.devnet]
cardinal_rewards_center = "E2Wc4racSRRp8EBrMH3n1AYSjuFt4JiLdh14J58UiyDu"

[programs.testnet]
cardinal_rewards_center = "E2Wc4racSRRp8EBrMH3n1AYSjuFt4JiLdh14J58UiyDu"

[programs.localnet]
cardinal_rewards_center = "E2Wc4racSRRp8EBrMH3n1AYSjuFt4JiLdh14J58UiyDu"
